---
title: "Plotathon"
output: html_document
date: "2024-02-23"
---

## Import from dataset

```{r setup, include=FALSE}
library(tidyverse)

data <- read_csv('Datasheet.csv', show_col_types = FALSE)

#summary(data)
#data2 <- distinct(data)
#missing_values <- colSums(is.na(data))
#data2 <- na.omit(data)

data <- mutate(data,WeightedStar = `Review Count` * `Stars`)

MISSING <- is.na(data$"Good For Kids")

df<-data[!grepl("Beach", data$Categories),]
df<-df[!grepl("Park", df$Categories),]
df<-df[!grepl("Hiking", df$Categories),]

df1 <- data[complete.cases(data[['Good For Kids']]), ]

column_to_parse <- df$Categories

# Split the strings in the column by ", " to create a list of items
split_items <- strsplit(column_to_parse, ", ")

# Flatten the list to count the occurrences of each item
all_items <- unlist(split_items)


# Count the occurrences of each unique item in the column
item_counts <- table(all_items)

# Display the counts
print(item_counts)


summary(df1)

```

ll as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r data}
pat <- "\\Hotel\\b"
Hoteldf<-data[grepl("Hotel", data$Categories),]
newdf <- na.omit(Hoteldf)
print(newdf)
cor(newdf)
```
```{r}
library(stringr)

substring_to_search <- "none"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf$"Wi Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf$"Wi Fi"[substring_found] <- 1

substring_to_search <- "no"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf$"Wi Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf$"Wi Fi"[substring_found] <- 0

substring_to_search <- "free"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf$"Wi Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf$"Wi Fi"[substring_found] <- 1

substring_to_search <- "paid"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf$"Wi Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf$"Wi Fi"[substring_found] <- 1

substring_to_search <- "TRUE"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf, substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf[substring_found] <- 1

substring_to_search <- "FALSE"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf, substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf[substring_found] <- 0


print(Hoteldf)
cor(Hoteldf)

```
Devin Working

```{r}

Hoteldf2 <- read_csv('Hotels.csv', show_col_types = FALSE)

substring_to_search <- "none"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2$"Wi.Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2$"Wi.Fi"[substring_found] <- 1

substring_to_search <- "no"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2$"Wi.Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2$"Wi.Fi"[substring_found] <- 0

substring_to_search <- "free"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2$"Wi.Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2$"Wi.Fi"[substring_found] <- 1

substring_to_search <- "u"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2$"Wi.Fi", substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2$"Wi.Fi"[substring_found] <- 1

substring_to_search <- "TRUE"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2, substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2[substring_found] <- 1

substring_to_search <- "FALSE"

# Check if the substring_to_search is found in each element of column_to_modify
substring_found <- str_detect(Hoteldf2, substring_to_search)

# Replace the cells in the column where the substring is found with 1, otherwise leave them unchanged
Hoteldf2[substring_found] <- 0


num <- Hoteldf2 %>% mutate_at(c('Wi.Fi', 'Bike.Parking', "Accepts.Credit", "Dogs.Allowed", "Good.For.Kids", "Has.TV"), as.numeric)

names_num <- names(which(sapply(num, is.numeric)))
num <- num[, names_num]
cor(num)

```
```{r }
summary(num)

num <- Hoteldf2 %>% mutate_at(c('Wi.Fi', 'Bike.Parking', "Accepts.Credit", "Dogs.Allowed", "Good.For.Kids", "Has.TV"), as.numeric)

names_num <- names(which(sapply(num, is.numeric)))
num <- num[, names_num]
cor(num)
```
```{r}
drop <- c("Wheelchair.Accessible","Restaurants.Table.Service", "Restaurants.Reservations", "Restaurants.Take.Out", "Delivery", "Restaurants.Good.For.Groups", "Bike.Parking", "Accepts.Credit",  "Dogs.Allowed", "Good.For.Kids", "Has.TV",  "Outdoor.Seating")
df2 = num[,!(names(num) %in% drop)]

write.csv(df2, "Hoteldata.csv")
```

